<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="AAD-W17Q1DRL3" failures="4" tests="5" name="APIM_CustomAPI" time="281.587" errors="0" timestamp="15 Dec 2022 18:03:42 GMT">
  <testcase classname="com.informatica.tests.CustomAPITest" name="ValdiateTestAndCreateCustomAPI" time="51.118"/>
  <testcase classname="com.informatica.tests.CustomAPITest" name="ValdiateAddRatelimitToCustomApi" time="4.919">
    <failure type="java.lang.AssertionError" message="expected [The Managed API &amp;quot;CustomAPI_Automation&amp;quot; was updated successfully.] but found [Failed to update the Managed API &amp;quot;CustomAPI_Automation&amp;quot;]">
      <![CDATA[java.lang.AssertionError: expected [The Managed API "CustomAPI_Automation" was updated successfully.] but found [Failed to update the Managed API "CustomAPI_Automation"]
at com.informatica.tests.CustomAPITest.ValdiateAddRatelimitToCustomApi(CustomAPITest.java:119)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- ValdiateAddRatelimitToCustomApi -->
  <testcase classname="com.informatica.tests.CustomAPITest" name="ValdiateAddIpFilteringToCustomApi" time="60.008">
    <failure type="java.lang.AssertionError" message="Exception while validating  update IpFiltering for CustomAPI">
      <![CDATA[java.lang.AssertionError: Exception while validating  update IpFiltering for CustomAPI
at com.informatica.tests.CustomAPITest.ValdiateAddIpFilteringToCustomApi(CustomAPITest.java:167)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- ValdiateAddIpFilteringToCustomApi -->
  <testcase classname="com.informatica.tests.CustomAPITest" name="ValdiateAddGroupToCustomApi" time="60.016">
    <failure type="java.lang.AssertionError" message="Exception while validating  update Groups for CustomAPI">
      <![CDATA[java.lang.AssertionError: Exception while validating  update Groups for CustomAPI
at com.informatica.tests.CustomAPITest.ValdiateAddGroupToCustomApi(CustomAPITest.java:202)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- ValdiateAddGroupToCustomApi -->
  <testcase classname="com.informatica.tests.CustomAPITest" name="ValdiateDeleteCustomAPI" time="60.009">
    <failure type="java.lang.AssertionError" message="Exception while validating  Delete Custom API">
      <![CDATA[java.lang.AssertionError: Exception while validating  Delete Custom API
at com.informatica.tests.CustomAPITest.ValdiateDeleteCustomAPI(CustomAPITest.java:231)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- ValdiateDeleteCustomAPI -->
</testsuite> <!-- APIM_CustomAPI -->
